RULES_MESSAGE:
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
HELP_MESSAGE:
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
UP_SIGN_CREATE_TEXT:
  - "[Elevator]"
  - "Up"
UP_SIGN_TEXT:
  - "&5Up Elevator"
  - "&eClick to use"
DOWN_SIGN_CREATE_TEXT:
  - "[Elevator]"
  - "Down"
DOWN_SIGN_TEXT:
  - "&5Down Elevator"
  - "&eClick to use"