SUBCLAIM:
  ENABLED: TRUE
  CREATE_TEXT: "[SUBCLAIM]"
DATABASE:
  MONGO:
    DATABASE: "Horus"
    HOST: "127.0.0.1"
    PORT: 27017
    AUTHENTICATION:
      ENABLED: FALSE
      DATABASE: "Horus"
      USER: "user"
      PASSWORD: "password"
BLOCK_MODIFIER:
  FURNACE_COOK_INCREASE: 10
  BREWING_STAND_BREW_INCREASE: 10
COMBAT_LOGGER:
  ENTITY_TYPE: "VILLAGER"
  DESPAWN_TIME: 30
  LOGOUT_TIME: 30
  LOGOUT_CANCEL_RANGE: 1
BLOCKED_POTIONS: #put the data value
  - 8201
  - 8233
  - 16393
  - 8265
  - 16425
  - 16457
  - 16420
  - 8228
  - 8193
  - 8225
  - 8257
  - 16385
  - 16417
  - 16449
  - 16452
  - 8260
  - 8232
  - 8264
  - 16424
  - 16456
  - 8266
  - 16458
  - 8268
  - 8236
  - 16460
  - 16428
ENCHANTMENT_LIMITER:
  DAMAGE_ALL: 1
  PROTECTION_ENVIRONMENTAL: 1
  ARROW_DAMAGE: 3
  ARROW_KNOCKBACK: 0
  FIRE_ASPECT: 0
  KNOCKBACK: 0
  THORNS: 0
COOLDOWN:
  ENDER_PEARL: 16
  SPAWN_TAG: 30
PVP_PROTECTION:
  DURATION: 1800
CROWBAR:
  ITEM: "DIAMOND_HOE"
CLAIM_WALL:
  PVP_PROTECTION:
    RANGE: 10
    SIZE: 10
    BLOCK: "STAINED_GLASS"
    DATA: 2
  SPAWN_TAG:
    RANGE: 10
    SIZE: 10
    BLOCK: "STAINED_GLASS"
    DATA: 14
KIT:
  ARCHER_TAG:
    DURATION: 10
    INCREASE: 1.15
  ABILITY:
    SINGLE_SUGAR_SPEED:
      DURATION: 10
      COOLDOWN_DURATION: 30
      LEVEL: 4
    MULTI_SUGAR_SPEED:
      ENERGY_REQUIRED: 5
      DURATION: 10
      LEVEL: 3
      RANGE: 15
      ITEM: "SUGAR"
    MULTI_FEATHER_JUMP:
      ENERGY_REQUIRED: 5
      DURATION: 10
      LEVEL: 6
      RANGE: 15
      ITEM: "FEATHER"
    MULTI_IRON_RESISTANCE:
      ENERGY_REQUIRED: 5
      DURATION: 10
      LEVEL: 3
      RANGE: 15
      ITEM: "IRON_INGOT"
    MULTI_BLAZE_STRENGTH:
      ENERGY_REQUIRED: 5
      DURATION: 10
      LEVEL: 2
      RANGE: 15
      ITEM: "BLAZE_POWDER"
    MULTI_SPIDER_WITHER:
      ENERGY_REQUIRED: 5
      DURATION: 10
      LEVEL: 2
      RANGE: 15
      ITEM: "SPIDER_EYE"
    MULTI_TEAR_REGEN:
      ENERGY_REQUIRED: 5
      DURATION: 10
      LEVEL: 2
      RANGE: 15
      ITEM: "GHAST_TEAR"
    MULTI_CREAM_FIRERES:
      ENERGY_REQUIRED: 5
      DURATION: 10
      LEVEL: 2
      RANGE: 15
      ITEM: "MAGMA_CREAM"
  WARMUP:
    ENABLED: TRUE
    TIME: 10
MOB_STACKING:
  MAX_COUNT: 175
  NO_AI:
    - "SKELETON"
    - "ZOMBIE"
    - "CREEPER"
    - "PIG"
    - "COW"
    - "SHEEP"
    - "VILLAGER"
    - "CHICKEN"
  EXCLUDED_MOBS:
    - "CREEPER"
    - "ENDERMAN"
    - "SLIME"
    - "BAT"
    - "HORSE"
    - "VILLAGER"
KOTH:
  KEY:
    COMMAND: "crate key give %PLAYER% koth 1"
ENCHANTS:
  RUNNABLE:
    ENABLED: false
  SPEED: false
  FIRE: false