name: GGA
version: ${version}
main: net.psychz.gga.bukkit.BukkitSide
depend: [ProtocolLib]
authors: [suedadam, Sponges]
description: Psychz's GGA platform plugin able to be used on both Bukkit/Spigot and BungeeCord. 

