MESSAGE.LOADEDPROFILE: "&aYour profile has been loaded from the database!"
MESSAGE.LOADINGPROFILE": "&aYour profile is loading from the database!"
MESSAGE.PERMISSION: "&cYou dont have permission to use this command!"
ESSAGE.BLACKLIST: "&4 Has been Blacklisted"
MESSAGE.UNBLACKLIST: "&aPlayer has been unblacklisted!"
MESSAGE.BLACKLIST.LOGIN: "&4You have been blacklisted from this network"

MESSAGE_HELP:
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 
MESSAGE_RULES:
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"
 - "adsad"