rank.owner: '&4Owner'
rank.developer: '&eDeveloper'
rank.manager: '&aStaff Manager'
rank.junioradmin: '&cJunior Admin'
rank.senioradmin: '&cSenior Admin'
rank.admin: '&cAdmin'
rank.seniormod: '&5Senior Mod'
rank.moderator: '&3Moderator'
rank.trialmod: '&9Trial Mod'
rank.default: '&fNormal'
rank.silver: '&7Silver'
rank.gold: '&6Gold'
rank.redstone: '&cRedstone'
rank.lapis: '&9Lapis'
rank.diamond: '&bDiamond'
rank.emerald: '&aEmerald'
rank.wenja: '&5Wenja'
rank.famous: '&d&oFamous'
rank.youtuber: '&dYouTuber'
rank.twitch: '&5&oTwitch'
rank.champion: '&9Champion'
