RULES_MESSAGE:
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
HELP_MESSAGE:
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"
 - "RULES 1"