name: WenjaSecurity
version: 1.2
main: net.rifthq.typa.Typa
author: [puttydotexe, Mans]
commands:
  register: 
    description: Command used to register a staff account.
  login: 
     description: Command used to log into a staff account. 
  resetpin:
     description: Command used to reset a staff accounts pin.
  resetplayer: 
     description: Command used to reset a staff account.